export const menu = [
    {
        id: 1.1,
        nombre: "Tabla de charcuteria",
        categoria: "entrada",
        descripcion: "tabla de jamones curados, quesos, frutos secos,tomate deshidratado, mix de aceituna, manzanas, mermelada, pan artesanal y trufas de chocolate",
        img: "./img/menu/entradas/1.1.jpg",
        precio: 250,
    },
    {
        id: 1.2,
        nombre: "Fuego del mar", 
        categoria: "entrada",
        descripcion: "camarones en tempura con una salsa dulce y sutilmente picante, aguacate, tomate, cilantro y crema. plato estrella",
        img: "./img/menu/entradas/Fuego-del-mar-FB.jpg",
        precio: 120,
    },
    {
        id: 1.3,
        nombre: "Carpaccio de res",
        categoria: "entrada",
        descripcion: "Lomito, queso parmesano, cebolla morada, alcaparras, arúgula, aceite de oliva y limón.",
        img: "./img/menu/entradas/1.3.jpg",
        precio: 79,
    },
    {
        id: 1.4,
        nombre: "Jalapeño poppers",
        categoria: "entrada",
        descripcion: "jalapeño en tempura relleno con dip de queso crema con especias y tocino enrollado",
        img: "./img/menu/entradas/Jalapeño-poppers-FB2.jpg",
        precio: 65,
    },
    {
        id: 1.5,
        nombre: "Veggie poppers",
        categoria: "entrada", 
        descripcion: "jalapeño en tempura relleno con dip de queso crema con especias.",
        img: "./img/menu/entradas/1.5.jpg",
        precio: 65,
    },
    {
        id: 1.6,
        nombre: "Tamalito de elote",
        categoria: "entrada", 
        descripcion: "Platillo agridulce, salsa verde, pico de gallo, crema, mousse de aguacate y chipotle.",
        img: "./img/menu/entradas/1.6.jpg",
        precio: 60,
    },
    {
        id: 1.7,
        nombre: "Ensalada caprese",
        categoria: "entrada",
        descripcion: "Tomate, mozzarella fresca, pesto, reduccion de vinagre balsamico y aceite de oliva.",
        img: "./img/menu/entradas/Ensalada -caprese-FB.jpg",
        precio: 60,
    },
    {
        id: 1.8,
        nombre: "Huevos gourmet",
        categoria: "entrada", 
        descripcion: "Huevos duros, yema infusionada con mostaza, mayonesa y poco pimenton",
        img: "./img/menu/entradas/1.8.jpg",
        precio: 55,
    },
    {
        id: 1.9,
        nombre: "Aros de cebolla",
        categoria: "entrada", 
        descripcion: "Con tempura de cerveza",
        img: "./img/menu/entradas/1.9.jpg",
        precio: 55,
    },
    {
        id: 1.10,
        nombre: "Beer battered fries",
        categoria: "entrada", 
        descripcion: "Papas fritas con tempura de cerveza",
        img: "./img/menu/entradas/1.10.jpg",
        precio: 55,
    },
    {
        id: 1.11,
        nombre: "chips de camote",
        categoria: "entrada", 
        descripcion: "rodajas semifinas de camote frito en aceite.",
        img: "./img/menu/entradas/1.11.jpg",
        precio: 45,
    },
    {
        id: 1.12,
        nombre: "Elote picante",
        categoria: "entrada", 
        descripcion: "Granos de maiz dulce, chiles secos, cilantro y queso parmesano",
        img: "./img/menu/entradas/1.12.jpg",
        precio: 45,
    },
    /*----  TACOS -----*/
    {
        id: 2.1,
        nombre: "Tacos del mar y fuego",
        categoria: "tacos", 
        descripcion: "camarones en tempura con una salsa dulce y sutilmente picante,  aguacate, tomate, cilantro y crema.",
        img: "./img/menu/tacos/2.1.jpg",
        precio: 99,
    },
    {
        id: 2.2,
        nombre: "Tacos al pastor",
        categoria: "tacos", 
        descripcion: "cerdo desmenuzado con salsa de adobo, cebolla caramelizada y cubos de piña.",
        img: "./img/menu/tacos/Tacos -al-pastor-FB.jpg",
        precio: 80,
    },
    {
        id: 2.3,
        nombre: "Tacos de res",
        categoria: "tacos", 
        descripcion: "Lomito, cebolla salteada, aguacate, crema y pico de gallo",
        img: "./img/menu/tacos/2.3.jpg",
        precio: 45,
    },
    {
        id: 2.4,
        nombre: "Tacos de pescado",
        categoria: "tacos", 
        descripcion: "Tilapia en tempura, aguacate, repollo y chipotle.",
        img: "./img/menu/tacos/Tacos-de-pescado-FB.jpg",
        precio: 85,
    },
    {
        id: 2.5,
        nombre: "Tacos de pulled pork",
        categoria: "tacos", 
        descripcion: "Cerdo desmenuzado, cebolla salteada y mousse de aguacate.",
        img: "./img/menu/tacos/2.5.jpg",
        precio: 80,
    },
    {
        id: 2.6,
        nombre: "Tacos de pollo",
        categoria: "tacos", 
        descripcion: "Pollo desmenuzado, cebolla salteada, cilantro, aguacate, pico de gallo y chipotle.",
        img: "./img/menu/tacos/tacos-de-pollo-FB2.jpg",
        precio: 75,
    },
    {
        id: 2.7,
        nombre: "Burrito de res",
        categoria: "tacos", 
        descripcion: "Tortilla de harina , lomito , cebolla salteada, frijol, queso, aguacate, pico de gallo y chipotle.",
        img: "./img/menu/tacos/2.7.jpg",
        precio: 95,
    },
    {
        id: 2.8,
        nombre: "Burrito de pollo",
        categoria: "tacos", 
        descripcion: "Tortilla de harina, pollo, cebolla salteada, frijol, queso, aguacate, pico de gallo y chipotle.",
        img: "./img/menu/tacos/2.8.jpg",
        precio: 75,
    },
    {
        id: 2.9,
        nombre: "Quesadilla de res",
        categoria: "tacos", 
        descripcion: "Tortilla de harina, lomito, queso, cebolla , chile pimiento salteado, costra de queso cheddar y jalapeño.",
        img: "./img/menu/tacos/2.9.jpg",
        precio: 95,
    },
    {
        id: 2.10,
        nombre: "Quesadilla de pollo",
        categoria: "tacos", 
        descripcion: "Tortilla de harina, pollo, queso, cebolla, chile pimiento salteado, costra  de queso cheddar y jalapeño.",
        img: "./img/menu/tacos/2.10.jpg",
        precio: 75,
    },
    /*--    BARBACOA    --*/
    {
        id: 3.1,
        nombre: "BBQ mar y tierra",
        categoria: "barbacoa", 
        descripcion: "3/4 lb Baby back ribs cocinadas por 24 horas en sous vide [al vacio] 1/2 lb de camarones jumbo asados y elote dulce asado.",
        img: "./img/menu/barbacoa/3.1.jpg",
        precio: 290,
    },
    {
        id: 3.2,
        nombre: "Fire grilled shrimp",
        categoria: "barbacoa", 
        descripcion: "1/2 lb de camarones jumbo asados, elote dulce asado, vegetales salteados.",
        img: "./img/menu/barbacoa/3.2.jpg",
        precio: 170,
    },
    {
        id: 3.3,
        nombre: "Fire grilled salmon",
        categoria: "barbacoa", 
        descripcion: "1/2 de salmon asado. Salsa de pesto ligera. Púre de papa y vegetales salteados.",
        img: "./img/menu/barbacoa/3.3.jpg",
        precio: 160,
    },
    {
        id: 3.4,
        nombre: "Baby back ribs",
        categoria: "barbacoa", 
        descripcion: "costillas cocinadas por 24hrs en sous vide [al vacio]. salsa de tu elección. pure de papa y vegetales salteados 3/4lb  Q129 o 1.25lb Q225",
        img: "./img/menu/barbacoa/3.4.jpg",
        precio: 99,
    },
    {
        id: 3.5,
        nombre: "BBQ rib sandwich",
        categoria: "barbacoa", 
        descripcion: "costilla baby back con “la perfecta” salsa barbacoa, pepinillos y cebolla encurtida. chips de camote",
        img: "./img/menu/barbacoa/3.5.jpg",
        precio: 75,
    },
    {
        id: 3.6,
        nombre: "BBQ sliders",
        categoria: "barbacoa", 
        descripcion: "Panes brioche rellenos cerdo desmenuzado con salsa barbacoa. Chips de camote.",
        img: "./img/menu/barbacoa/3.6.jpg",
        precio: 75,
    },
    {
        id: 3.7,
        nombre: "BBQ wings",
        categoria: "barbacoa", 
        descripcion: "Alitas asadas. Salsa de tu eleccion. Con crudités. 12 Q130 o 6 Q70",
        img: "./img/menu/barbacoa/BBQ-wings-FB.jpg",
        precio: 75,
    },
    /*---VEGETARIANOS---*/
    {
        id: 4.1,
        nombre: "World’s best veggie",
        categoria: "vegetarianos", 
        descripcion: "Veggie Burger de beyond meat, queso, champiñones, cebolla salteada y tomate semi deshidratado, chips de camote",
        img: "./img/menu/vegetariano/4.1.jpg",
        precio: 99,
    },
    {
        id: 4.2,
        nombre: "Veggie tacos",
        categoria: "vegetarianos", 
        descripcion: "Tres tortillas de maiz, con costra de mozzarella, cebolla, chile pimeinto, champiñones salteados, aguacate, pico de gallo y chipotle.",
        img: "./img/menu/vegetariano/4.2.jpg",
        precio: 75,
    },
    {
        id: 4.3,
        nombre: "Veggie quesadilla",
        categoria: "vegetarianos", 
        descripcion: "Tortilla de harina, queso y cebolla, chile pimiento salteado, costra de queso cheedar y jalapeño.",
        img: "./img/menu/vegetariano/4.3.jpg",
        precio: 75,
    },
    {
        id: 4.4,
        nombre: "Ensaladas cesar",
        categoria: "vegetarianos", 
        descripcion: "Lechuga, crutones, queso parmesano y aderezo cesar.",
        img: "./img/menu/vegetariano/4.4.jpg",
        precio: 65,
    },
    {
        id: 4.5,
        nombre: "Ensalada del sur",
        categoria: "vegetarianos", 
        descripcion: "Lechuga aguacate, frijoles, tomate, elotitos, cilantro, chips de tortillas y aderezo de chipotle.",
        img: "./img/menu/vegetariano/4.5.jpg",
        precio: 65,
    },
    {
        id: 4.6,
        nombre: "Ensalada griega",
        categoria: "vegetarianos", 
        descripcion: "Lechuga, queso freta, aceitunas, cebolla morada, pepino, cilantro, chile pimiento escalfado, aceite de oliva y limón.",
        img: "./img/menu/vegetariano/4.6.jpg",
        precio: 65,
    },
    {
        id: 4.7,
        nombre: "Ensalada del chef",
        categoria: "vegetarianos", 
        descripcion: "Lechuga, elotitos, pepino, cebolla morada, tomate, huevos groumet, queso cheddar y aderezo ranch.",
        img: "./img/menu/vegetariano/4.7.jpg",
        precio: 65,
    },
    /*-----PIZZAS-----*/
    {
        id: 5.1,
        nombre: "Las tres amigas",
        categoria: "pizzas", 
        descripcion: "pepperoni, jamon, tocino y salsa de tomate.",
        img: "./img/menu/pizzas/5.1.jpeg",
        precio: 130,
    },
    {
        id: 5.2,
        nombre: "the BBQ ONE",
        categoria: "pizzas", 
        descripcion: "Pulled pork con salsa barbacoa y rodajas de jalapeño.",
        img: "./img/menu/pizzas/5.2.jpg",
        precio: 130,
    },
    {
        id: 5.3,
        nombre: "prosciutto",
        categoria: "pizzas", 
        descripcion: "Prosciutto, arugula, reduccion de vinagre balsamico y salsa de tomate",
        img: "./img/menu/pizzas/5.3.gif",
        precio: 130,
    },
    {
        id: 5.4,
        nombre: "la volatil",
        categoria: "pizzas", 
        descripcion: "Dátiles, queso de cabra, arúgala y reducción de vinagre balsámico.",
        img: "./img/menu/pizzas/5.4.jpeg",
        precio: 130,
    },
    {
        id: 5.5,
        nombre: "Pepperoni y jamón",
        categoria: "pizzas", 
        descripcion: "Pepperoni o jamon, champiñones salteados y salsa de tomate.",
        img: "./img/menu/pizzas/5.5.jpeg",
        precio: 120,
    },
    {
        id: 5.6,
        nombre: "Margarita",
        categoria: "pizzas", 
        descripcion: "Tomate cherries, mozzallela fresca, aceite de albahaca y salsa de tomate",
        img: "./img/menu/pizzas/5.6.jpg",
        precio: 120,
    },
    {
        id: 5.7,
        nombre: "Hawaiana",
        categoria: "pizzas", 
        descripcion: "Jamon, cubos de piña, coulis de piña con pimienta cayena y salsa de tomate.",
        img: "./img/menu/pizzas/5.7.jpg",
        precio: 120,
    },
    /*-----HAMBURGUESAS-----*/
    {
        id: 6.1,
        nombre: "El brisket",
        categoria: "hamburguesas", 
        descripcion: "Torta de birsket molido, queso, champiñones salteados, cebolla salteada y tomate semi deshidratado.",
        img: "./img/menu/hamburguesas/6.1.jpg",
        precio: 125,
    },
    {
        id: 6.2,
        nombre: "Triple Smash Burger",
        categoria: "hamburguesas", 
        descripcion: "Tres tortas prensadas con queso, aderezo de la casa",
        img: "./img/menu/hamburguesas/6.2.jpg",
        precio: 119,
    },
    {
        id: 6.3,
        nombre: "Doublé smash Burger",
        categoria: "hamburguesas", 
        descripcion: "Dos tortas prensadas con queso, aderezo de la casa",
        img: "./img/menu/hamburguesas/6.3.jpg",
        precio: 110,
    },
    {
        id: 6.4,
        nombre: "Sur Oeste Gourmet",
        categoria: "hamburguesas", 
        descripcion: "Mermelada de tocino y cebolla caramelizada, queso, tomate y lechuga.",
        img: "./img/menu/hamburguesas/6.4.jpg",
        precio: 110,
    },
    {
        id: 6.5,
        nombre: "Sweet Jalapeño",
        categoria: "hamburguesas", 
        descripcion: "Mermelada de jalapeño, queso, tomate, y lechuga",
        img: "./img/menu/hamburguesas/6.5.jpg",
        precio: 110,
    },
    {
        id: 6.6,
        nombre: "Aleluya Jalapeño",
        categoria: "hamburguesas", 
        descripcion: "Jalapeño y cebolla salteada, queso, pepinillos, tomate y lechuga",
        img: "./img/menu/hamburguesas/6.6.jpg",
        precio: 110,
    },
    {
        id: 6.7,
        nombre: "Bacon Burger",
        categoria: "hamburguesas", 
        descripcion: "Bacon Burger",
        img: "./img/menu/hamburguesas/6.7.jpg",
        precio: 105,
    },
    {
        id: 6.8,
        nombre: "Classic Burger",
        categoria: "hamburguesas", 
        descripcion: "Queso, aderezo de la casa, tomate, pepinillos y lechuga.",
        img: "./img/menu/hamburguesas/6.8.jpg",
        precio: 99,
    },
    /*-----SANDWICHS-----*/
    {
        id: 7.1,
        nombre: "Sándwich cubano",
        categoria: "sandwich", 
        descripcion: "Cerdo demenuzado, jamon dulce, salami, queso suizo, pepinillos y mostaza.",
        img: "./img/menu/sandwich/7.1.jpg",
        precio: 99,
    },
    {
        id: 7.2,
        nombre: "French dip sandwich",
        categoria: "sandwich", 
        descripcion: "Pan chapata relleno de carne de res desmenuzada, cebolla caramelizada, queso suizo y fondo de res.",
        img: "./img/menu/sandwich/7.2.jpeg",
        precio: 88,
    },
    {
        id: 7.3,
        nombre: "Grilled pollo",
        categoria: "sandwich", 
        descripcion: "Pan brioche, pollo asado, queso suizo, tocino, tomate y lechuga.",
        img: "./img/menu/sandwich/7.3.jpg",
        precio: 88,
    },
    {
        id: 7.4,
        nombre: "Tempura chicken",
        categoria: "sandwich", 
        descripcion: "Pan brioche, pollo en tempura, queso suizo, tomate y lechuga.",
        img: "./img/menu/sandwich/7.4.jpg",
        precio: 88,
    },
    {
        id: 7.5,
        nombre: "El italiano",
        categoria: "sandwich", 
        descripcion: "Baguette con prosciutto, arrúgala, mozzarella fresca, tomate y reducción de vinagre balsámico.",
        img: "./img/menu/sandwich/7.5.jpg",
        precio: 88,
    },
    
    /*-----POSTRES-----*/
    {
        id: 8.1,
        nombre: "Panna cotta",
        categoria: "postres", 
        descripcion: "Con chocolate blanco, servicio sobre un coulis de fresa, cumble y frutos rojos.",
        img: "./img/menu/postres/Panna-cotta-FB.jpg",
        precio: 60,
    },
    {
        id: 8.2,
        nombre: "Brownie con helado",
        categoria: "postres", 
        descripcion: "Brownie de chocolate y helado de vainilla.",
        img: "./img/menu/postres/Brownie-con-helado-FB.jpg",
        precio: 50,
    },
    {
        id: 8.3,
        nombre: "Key lime cheesecake",
        categoria: "postres", 
        descripcion: "Capas de pie de limon clasico, cheesecake de limon, galleta y crema batida, servido en un vaso.",
        img: "./img/menu/postres/Key -lime-cheesecake-FB.jpg",
        precio: 50,
    },
    {
        id: 8.4,
        nombre: "Reese’s cheesecake",
        categoria: "postres", 
        descripcion: "Cheesecake de mantequilla de mani, ganache de chocolate, galleta y crema batida, servido en un vaso.",
        img: "./img/menu/postres/Key -lime-cheesecake-FB.jpg",
        precio: 50,
    },
    {
        id: 8.5,
        nombre: "Soufflé de elote",
        categoria: "postres", 
        descripcion: "Pastel de elote dulce y cremoso, crema batida y almendras caramelizadas.",
        img: "./img/menu/postres/8.5.jpg",
        precio: 50,
    },
    {
        id: 8.6,
        nombre: "Ana fana fo fana",
        categoria: "postres", 
        descripcion: "Chimichanga infusionada con queso crema de fresa o nutella con banano y fresa, a eleccion servido con helado de vainilla.",
        img: "./img/menu/postres/8.6.jpeg",
        precio: 50,
    },
];

